services:
  mongo:
    image: mongo:6.0
    platform: linux/arm64/v8
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  llama:
    image: ollama/ollama:latest
    platform: linux/arm64/v8
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0

  gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    volumes:
      - ./backend/gateway:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - LLAMA_ENDPOINT=http://llama:11434/api/chat
      - LLAMA_MODEL=llama3:8b
    depends_on:
      - mongo
      - llama

  nextjs:
    build: ./frontend
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:8000
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - gateway

volumes:
  mongodb_data:
  ollama-data:
