version: "3"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    volumes:
      - ./backend/gateway:/app
    environment:
      - MONGO_URL=${MONGO_URL}
      - LLAMA_ENDPOINT=${LLAMA_ENDPOINT}
      - LLAMA_API_KEY=${LLAMA_API_KEY}
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:8000
      - GATEWAY_URL=http://gateway:8000
    command: npm run dev
