version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - LLAMA_ENDPOINT=${LLAMA_ENDPOINT}
      - LLAMA_API_KEY=${LLAMA_API_KEY}
      - THREADS_BASEURL=${THREADS_BASEURL}
    depends_on:
      - mongo

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - gateway

volumes:
  mongo_data:
